module.exports =
  [ '_id'
  , 'type'
  , 'shortTitle'
  , 'longTitle'
  , 'standfirst'
  , 'subTitle'
  , 'slug'
  , 'displayDate'
  , 'showDisplayDate'
  , 'tags'
  , 'commentCount'
  , 'viewCount'
  , 'section'
  ]